import Head from 'next/head';
import router from 'next/router';
import axios from 'axios';
import { useEffect, useState } from 'react';
import jwt from 'jsonwebtoken';

export default function Home({ appContext }) {

  const [screenWidth, setScreenWidth] = useState('');

  useEffect(() => {
    setScreenWidth(window.screen.width);
    appContext.setRenderSidebar(false);

    if (window.location.href.includes('#access_token')) {
      let token = window.location.href.split('#access_token=')[1].split('&')[0];
      localStorage.setItem('spotify_clone_token', jwt.sign(token, 'access_token_spotify2'));
      
    }

    if (localStorage.getItem('spotify_clone_token')) {
      router.push('/dashboard');
    
    }

  }, []);

  /*
    Linear gradient to be applied here
    Color top left: #EB47A9
    Color bottom right: #7642DD
    Redirect to -> https://www.spotify.com/in-en/download when clicked on 'GET SPOTIFY FREE'
    Letter spacing for the header_button_text is increased
    Put margin-inline for the div in the header section
    Apply display: flex, justify-content: space-around for the div in header section containing:
      1. Image
      2. Text
      3. 'GET SPOTIFY FREE' button
  */

  const handleLogin = () => {
    axios.get('http://localhost:3000/api/auth')
    .then(res => router.push(res.data.url));
  }

  const headerStyles = {
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundImage: 'linear-gradient(to bottom right, #EB47A9, #7642DD)',
    paddingTop: 30,
    paddingInline: 20
  };

  return (
    <div className='index-page'>
      <Head>
        <title>Spotify Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          position: 'sticky',
          top: 0,
          backgroundColor: 'black'
        }}
      >
        
        <img
          src='/logo.jpeg'
          style={{
            objectFit: 'contain',
            height: 100,
          }}
        />

        <button onClick={handleLogin} style={{marginRight: 15}} className='button primary'>Log into Spotify</button>
      </nav>

      <header style={headerStyles}>
        {screenWidth > 600 && <img style={{objectFit: 'contain', marginRight: 20}} src='/header_image.png' />}
        <p style={{
          fontSize: '52px',
          fontWeight: 900,
          color: 'white',
          marginBottom: 20,
        }}>
          Play millions of songs<br />and podcasts, for free.
        </p>
      </header>

      <section 
        style={{
          backgroundColor: 'white',
          paddingBlock: 40,
          paddingInline: 100,
        }}
      >
        <center>
          <p style={{
            fontSize: '40px',
            fontWeight: 900,
            color: 'black',
          }}>
            Why Spotify?
          </p><br /><br />

          <div
            style={{
              display: screenWidth > 1100 && 'flex',
              flexWrap: screenWidth > 1100 && 'wrap',
              justifyContent: screenWidth > 1100 && 'space-around',
            }}
          >

            <div style={{marginBottom: 30, maxWidth: 250}}>
              <img src='/section1.png' /><br /><br />
              <b><p style={{fontSize: '24px', color: 'black'}}>Play your favorites.</p></b>
              <p style={{fontSize: '14px', color: 'grey', marginTop: 10}}>
                Listen to the songs you love, and discover new music and podcasts.
              </p>
            </div>

            <div style={{marginBottom: 30, maxWidth: 250}}>
              <img src='/section2.png' /><br /><br />
              <b><p style={{fontSize: '24px', color: 'black'}}>Playlists made easy.</p></b>
              <p style={{fontSize: '14px', color: 'grey', marginTop: 10}}>
                We'll help you make playlists. Or enjoy playlists made by music experts.
              </p>
            </div>

            <div style={{marginBottom: 30, maxWidth: 250}}>
              <img src='/section3.png' /><br /><br />
              <b><p style={{fontSize: '24px', color: 'black'}}>Make it yours.</p></b>
              <p style={{fontSize: '14px', color: 'grey', marginTop: 10}}>
                Tell us what you like, and we'll recommend music for you.
              </p>
            </div>

            <div style={{marginBottom: 30, maxWidth: 250}}>
              <img src='/section4.png' /><br /><br />
              <b><p style={{fontSize: '24px', color: 'black'}}>Play</p></b>
              <p style={{fontSize: '14px', color: 'grey', marginTop: 10}}>
                To use less data when you play music, turn on Data Saver in Settings.
              </p>
            </div>

          </div>

        </center>
      </section>

      <section
        style={{
          backgroundImage: 'linear-gradient(to bottom right, #EB47A9, #7642DD)',
          paddingBlock: 150,
          paddingInline: 30,
        }}
      >
        <center>
          <p style={{
            fontSize: '52px',
            fontWeight: 900,
            color: 'white',
          }}>
            It's free.<br />No credit card required.
          </p>
        </center>
      </section>

    </div>
  );
}
